name: Manual
on:
  workflow_dispatch:
    inputs:
    greeteing:
      type: string
      default: Hello
      required: true
      description: A cheerful wrod
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo"${{inputs_greeting}}