name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:  # 👈 修正①：インデントを下げ、スペルを修正
        type: string
        default: Hello
        required: true
        description: A cheerful word # 👈 修正（タイポ）
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" # 👈 修正②③：半角スペースを入れ、ドット接続に修正